#!/usr/bin/env bash
# Offline generator for the committed WebAssembly spec-conformance fixtures
# (issue #163). This is NOT part of the build or CI: it runs once, by a
# maintainer, to regenerate the fixtures under `test/wasm-spec/`, which are then
# committed. The core stays zero-dependency — `zig build test` only loads the
# committed `.wasm` + `.json` via `@embedFile`, never `wast2json`.
#
# Requires `wast2json` from wabt (https://github.com/WebAssembly/wabt). On macOS:
#   brew install wabt
#
# Usage: scripts/gen_wasm_spec_fixtures.sh
#
# Pinned upstream revision and the curated group list are the single source of
# truth for the conformance surface; bump TESTSUITE_REV deliberately and re-run.
set -euo pipefail

# Pinned WebAssembly/testsuite commit. Bump deliberately and regenerate.
TESTSUITE_REV="193e551ff22663995b1ac95dc62344133669e14b"
RAW_BASE="https://raw.githubusercontent.com/WebAssembly/testsuite/${TESTSUITE_REV}"

# Curated subset covering the surface scoot-wasm implements. Keep this list in
# sync with the coverage table in docs/WASM_TOOLS.md. Excluded by construction:
# SIMD, threads, GC, exceptions, tail-call, multi-memory, linking/register, and
# the full Component Model (see issue #100 non-goals).
WAST_GROUPS=(
  i32
  i64
  conversions
  int_exprs
  int_literals
  address
  endianness
  memory_redundancy
  memory_fill
  local_get
  local_set
  call
  return
  br
  loop
  labels
  switch
  nop
  unreachable
  fac
  forward
)

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out_root="${repo_root}/test/wasm-spec"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

command -v wast2json >/dev/null 2>&1 || {
  echo "error: wast2json not found (install wabt: brew install wabt)" >&2
  exit 1
}

echo "Pinned WebAssembly/testsuite @ ${TESTSUITE_REV}"
rm -rf "${out_root}"
mkdir -p "${out_root}"

for group in "${WAST_GROUPS[@]}"; do
  echo "==> ${group}.wast"
  curl -fsSL -o "${work}/${group}.wast" "${RAW_BASE}/${group}.wast"
  mkdir -p "${out_root}/${group}"
  # wast2json emits <group>.json plus <group>.N.wasm (binary modules) and, for
  # text-form assert_malformed cases, <group>.N.wat (which the binary-only engine
  # cannot and should not consume — the runner skips those commands).
  wast2json "${work}/${group}.wast" \
    -o "${out_root}/${group}/${group}.json" >/dev/null
  # Drop text-form malformed artifacts: keep the fixture tree binary-only.
  rm -f "${out_root}/${group}/"*.wat
done

# Generate the comptime fixture index consumed by src/wasm_spec_test.zig. Every
# committed .json/.wasm is embedded so the runner is hermetic and comptime-checked.
index="${out_root}/fixtures.zig"
{
  echo "// GENERATED by scripts/gen_wasm_spec_fixtures.sh — do not edit by hand."
  echo "// WebAssembly/testsuite @ ${TESTSUITE_REV}"
  echo "//"
  echo "// Curated subset of the upstream spec test suite, converted offline with"
  echo "// wast2json (wabt). Loaded via @embedFile so \`zig build test\` needs no"
  echo "// external toolchain and the core stays zero-dependency (issue #163)."
  echo ""
  echo "pub const testsuite_rev = \"${TESTSUITE_REV}\";"
  echo ""
  echo "pub const Module = struct { name: []const u8, bytes: []const u8 };"
  echo "pub const Group = struct {"
  echo "    name: []const u8,"
  echo "    json: []const u8,"
  echo "    modules: []const Module,"
  echo "};"
  echo ""
  echo "pub const groups = [_]Group{"
  for group in "${WAST_GROUPS[@]}"; do
    echo "    .{"
    echo "        .name = \"${group}\","
    echo "        .json = @embedFile(\"${group}/${group}.json\"),"
    echo "        .modules = &.{"
    for wasm in "${out_root}/${group}/"*.wasm; do
      [ -e "${wasm}" ] || continue
      base="$(basename "${wasm}")"
      echo "            .{ .name = \"${base}\", .bytes = @embedFile(\"${group}/${base}\") },"
    done
    echo "        },"
    echo "    },"
  done
  echo "};"
} > "${index}"

echo "Wrote ${index}"
echo "Done: $(find "${out_root}" -name '*.wasm' | wc -l | tr -d ' ') modules across ${#WAST_GROUPS[@]} groups."
